### ISSUE TITLE
Use inheritance for the various types of a thing

### ISSUE THREAD

**Issue by aradalvand** [TelegramBots/Telegram.Bot#1088]
Hi there. Currently, whenever an update comes in, for example, you need to check the value of the `update.Type` property and then use the corresponding property on the `update` object to access the relevant information:
```csharp
public async Task HandleUpdateAsync(ITelegramBotClient bot, Update update, CancellationToken cancellationToken)
{
    if (update.Type == UpdateType.ChannelPost)
    {
        var channelPost = update.ChannelPost;
        // ...
    }
}
```
But this is clearly kind of awkward, this seems like a PERFECT use case for inheritance, and the `is` operator, right?!
```csharp
public async Task HandleUpdateAsync(ITelegramBotClient bot, Update update, CancellationToken cancellationToken)
{
    if (update is ChannelPost channelPost)
    {
        // ...
    }
}
```

I'm curious as to why the library wasn't designed this way, because it makes much, much more sense like this. This applies to things like `Message.Type`, etc. as well.

Thank you.

**Comment by karb0f0s** [comment]
Could you provide code for this change? Since Update lacks determinator field out of the box, it would require custom serializer which should decide with type of update we received. This might lead to increased resource usage and an overall slowdown. If you can provide us with a prototype (preferably with benchmark measurements) we would gladly implement this change.

**Comment by tuscen** [comment]
> I'm curious as to why the library wasn't designed this way, because it makes much, much more sense like this. This applies to things like Message.Type, etc. as well.

Mostly because official documentation and the API lack any way to know the type beforehand. 

Although with `Update` type it's quite easy to determine the type, it's a completely different story for `Message` type where we can't really subdivide it into a hierarchy because we have no way to know to sure which fields can be present in each type of a message.

**Comment by AradAlvand** [comment]
https://t.me/+DEff3_clxtJjODM8
