### ISSUE TITLE
Change error handling behaviour

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1106]
Consider capturing exceptions in Event Handler  and forwarding them to Error Handler.

**Comment by dezared** [comment]
a fix is ​​planned, a possible solution to this problem? I don't want the bot to shut down due to an error

**Comment by Fedorus** [comment]
@dezared you should handle errors of your code yourself

**Comment by karb0f0s** [comment]
We are prototyping it in a separate branch, but unfortunately there's no milestone for this feature.

**Comment by rivancic** [comment]
> @dezared you should handle errors of your code yourself

This is like saying if you integrate a library in your backend application at a bank, and you send wrong request, instead of getting 400 or 404 HTTP message that you then handle or exception for that matter and continue with your logic instead this will cause your library to not respond anymore until you restart your whole service. 
It doesn't make sense to me, or I'm missing something.

**Comment by wiz0u** [comment]
done in v21.3
