### ISSUE TITLE
UpdateType PollAnswer Dosent work

### ISSUE THREAD

**Issue by Ahron333** [TelegramBots/Telegram.Bot#1276]
Hey, for some reason it wont Update.PoolAnswer
sending pool to my client he is answering and nothing on "Update.PoolAnswer" wont even run the code throw.
`case UpdateType.PollAnswer:
                    {
                        MessageBox.Show(e.PollAnswer.User.ToString());
                    }
                    break;`

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
