### ISSUE TITLE
Missing documentation InputOnlineFile => InputFileUrl

### ISSUE THREAD

**Issue by gusarov** [TelegramBots/Telegram.Bot#1304]
Hello, I'm upgrading v15 to v19 right now, and noticed that after v16 there are bunch of missing items in the change log. One of the most difficult for me was InputOnlineFile => InputFileUrl, it took quite a while, had to analyze a history and wrap my head around internals. Please, consider to add this to the documentation / change log.

![image](https://github.com/TelegramBots/Telegram.Bot/assets/1462777/3aab3147-eb12-40a9-8670-dc23506d43bd)

![image](https://github.com/TelegramBots/Telegram.Bot/assets/1462777/fb75de83-962d-467d-918f-d18e422c1869)

![image](https://github.com/TelegramBots/Telegram.Bot/assets/1462777/19784049-b4fc-44d7-8bc9-efcc87ac256d)

**Comment by karb0f0s** [comment]
We keep documentation in a separate repository. These changes are covered in [Migration guide for version 19.0](https://telegrambots.github.io/book/Migration-Guide-to-Version-19.x.html#migration-guide-for-version-190)

**Comment by karb0f0s** [comment]
We would gladly approve any PR with improvements to our changelog.

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
