### ISSUE TITLE
Erro não autorizado 

### ISSUE THREAD

**Issue by diamondcontrol** [TelegramBots/Telegram.Bot#1320]
quando rodo a api da o seguinte erro:
Telegram.Bot.Exceptions.ApiRequestException: 'Unauthorized'

inclui 

API_id do aplicativo
API_hash do aplicativo

como deixado aqui no codigo porem recebo essa msg como posso resolver isso?
tambem não consegui acessar eu API_hash do aplicativo onde posso pegar essas informações para apagar e recriar?

**Comment by Fedorus** [comment]
Just from naming it looks like you are trying to use user api credentials in bot library 
PS: Please use english

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
