### ISSUE TITLE
GlobalUsings affects consuming projects

### ISSUE THREAD

**Issue by kemsky** [TelegramBots/Telegram.Bot#1446]
So now when I install `Telegram.Bot` I suddenly start getting errors like ambiguous `IHttpClientFactory` reference:

```csharp
using Google.Apis.Http;

namespace Gmail.Services;

internal interface IGoogleHttpClientFactory : IHttpClientFactory
{
}
```

The problem is that `GlobalUsings.cs` will add that namespaces to every file in the consuming project without the consumer explicitly opting in.

It seems that MS did not provide an option to limit the scope of global usings to the project, so the only way left is to disable global usings .

*NuGet Package Version:*  22.1.3

*.NET Version:* 8.0.0

**Comment by wiz0u** [comment]
I think the issue is more related to this setting in your project csproj:
`    <ImplicitUsings>enable</ImplicitUsings>`

I'm still trying to understand how the compiler determines which `global using` this settings will inject in your project, but I don't think it's related to the `global usings` in our code:

I tried removing the line `global using System.Net.Http;` from our code and IHttpClientFactory would still be resolved automatically (only with ImplicitUsings enabled)
On the other hand, the type `Invoice` for example, isn't resolved automatically, even though we have a `global using Telegram.Bot.Types.Payments;`

**Comment by wiz0u** [comment]
ok I think the issue is linked to this line we added in our csproj
`<FrameworkReference Include="Microsoft.AspNetCore.App" />`

In turn, it will inject AspNetCore standard `global using` in your compilation.

Right now, I don't plan to remove this line from our csproj as it is necessary to provide useful configuration extensions for developers using Telegram.Bot with WebHook.
In the future we might move AspNetCore stuff in a separate package to avoid that dependency, but the short term solution for you is probably to disable  `<ImplicitUsings>` or resolve ambiguous reference by giving the full type name.
