### ISSUE TITLE
problem with webhook  InlineKeyboardButton

### ISSUE THREAD

**Issue by HosseinRahmati** [TelegramBots/telegram.bot#355]
### problem with webhook  InlineKeyboardButton

i have a problem with  telegram webhook inline keyboard
how can i get  click on inline buttons and edit a Message and inline button text
i define a button like bottom Line

 ```
keyboard_I = new InlineKeyboardMarkup(new[]
                            {
                                    new[]
                                    {
                                        new InlineKeyboardButton{ Text="1.1", Url="http://ElectricKala.com/"},
                                        new InlineKeyboardButton{Text="1.2",SwitchInlineQuery = "1.2"},
                                    },
                                    new[]
                                    {
                                        new InlineKeyboardButton{Text="2.1",CallbackData="CallbackQueryUpdate"},
                                        new InlineKeyboardButton{Text="2.2",SwitchInlineQuery="2.1"},
                                    },
                                   new[] // 3th row
                                   {
                                       new InlineKeyboardButton("3.1", "inline_3.1"),
                                       new InlineKeyboardButton("3.2", "inline_3.2"),
                                   },
                                   new[] // 3th row
                                   {
                                       new InlineKeyboardButton("4.1",callbackData:"wwww"),
                                       new InlineKeyboardButton("4.2","555"),
                                   }
                                });

```

in post method i have a switch case on UpdateType

```
 switch (update.Type)
            {
                case UpdateType.MessageUpdate:
                    //await bot.SendTextMessage(chatId: update.Message.Chat.Id, text: "MessageUpdate==>" + text, replyMarkup: main_menu_key);

                    if (text != null && text.Contains("help"))
                    {
                        await bot.SendChatActionAsync(update.Message.Chat.Id, ChatAction.RecordVideo);

                        //await Task.Delay(500);
                        await bot.SendTextMessageAsync(chatId: update.Message.Chat.Id, text: "choose", replyMarkup: keyboard_I);

                        //await bot.SendTextMessageAsync(update.Message.Chat.Id, "Choose", replyMarkup: keyboard);
                    }
                    break;
                case UpdateType.CallbackQueryUpdate:
                    await bot.SendTextMessageAsync(chatId: update.Message.Chat.Id, text: "22-CallbackQueryUpdate==>" + text, replyMarkup: keyboard_I);
                    //await bot.EditInlineMessageTextAsync(update.CallbackQuery.InlineMessageId, "test");
                    //await bot.AnswerCallbackQueryAsync(update.CallbackQuery.Id, text: "test");
                    break;
                case UpdateType.ChosenInlineResultUpdate:
                    await bot.SendTextMessageAsync(chatId: update.Message.Chat.Id, text: "22-ChosenInlineResultUpdate==>" + text, replyMarkup: keyboard_I);
                    
                    break;
                case UpdateType.InlineQueryUpdate:
                    await bot.SendTextMessageAsync(chatId: update.Message.Chat.Id, text: "22-InlineQueryUpdate==>" + text, replyMarkup: keyboard_I);
                    break;
                case UpdateType.EditedMessage:
                    await bot.SendTextMessageAsync(chatId: update.Message.Chat.Id, text: "22-EditedMessage==>" + text, replyMarkup: keyboard_I);
                    break;
            }

```

but only come to  case UpdateType.MessageUpdate:
and i cant get case UpdateType.CallbackQueryUpdate: 
i want edite Message and inline buttons text after click on a  Inline Keyboard Button
 
thanks

**Comment by pouladpld** [comment]
I tried your code. It works fine in the switch.
If you are using an `async` method to handle update event, make sure you catch the exceptions so debugging could be easier:

```c#
private async void BotOnOnUpdate(object sender, UpdateEventArgs updateEventArgs) {
   try { /* your switch */ }
   catch (Exception e) { 
      Debug.WriteLine(e);
      // throw;
   }
}
```

>  i want edite Message and inline buttons text after click on a Inline Keyboard Button

I guess you confused Inline Message and Inline Keys. Have a look at this modified version of your switch so it edits the message with its inline keys:
```c#
// inside switch
case UpdateType.CallbackQueryUpdate:
    await _bot.AnswerCallbackQueryAsync(
        update.CallbackQuery.Id, 
        text: "Editing the message");

    var markup = CreateInlineKeysMarkup();
    markup.InlineKeyboard[1][1].Text = "Edited inline key";
    
    await _bot.EditMessageTextAsync(
        update.CallbackQuery.Message.Chat.Id,
        update.CallbackQuery.Message.MessageId, 
        "Edited message",
        replyMarkup: markup);
    break;
```

**Comment by HosseinRahmati** [comment]
no in webhook web Api only we have a post method and my program never come to 
case UpdateType.CallbackQueryUpdate:
always comes to
case UpdateType.MessageUpdate:

**Comment by hamidr65** [comment]
Hi guys
I have same unresolved issue in my webhook telegram bot 
my post method don't call when an inline keyboard is pressed.
anyone used inlinekeyboard in webhook ?

**Comment by mastermehrdad** [comment]
Hi all...
the problem for not getting inline_query or callback_query , for some reason !!? is because the server returns an error 500 when using anything other than message type and therefore nothing returns to the bot.
this is what you will get if you check your webhook by using getwebhookinfo through your browser :  
"last_error_date":1498730987,"last_error_message":"Wrong response from the webhook: 500 Internal Server Error"
Again for some reason !!? i don't know why MrRoundRobin does not attend to questions and problems regarding webhooks as he does on console apps !!?
Therefore, it would be nice to hear from anyone who has solved this issue !!?

**Comment by MrRoundRobin** [comment]
@mastermehrdad Sorry for not responding to these questions. Currently I am very busy and don't have enough time to test these things. I respond to questions which I'm able to do from my phone.

I hope that I get some time next week to check the webhook problems

**Comment by HosseinRahmati** [comment]
use try catch and log errors in to a text file
a error restart my website application pool

**Comment by PurTahan** [comment]
Perhaps Your problem is in getting `update.Message.Chat.Id` or any Data in `update.Message'. Because in `inlineKeyboard` updates `update.type` is **Not** `MessageUpdate` and it is` CallbackQueryUpdate`.   
check your code and fix that....

**Comment by andrey-messi** [comment]
UP!!! Still 3 years later UpdateType.Message is the only one that works in webHook. 
I have this webhook initialization 
            Bot.Api.SetWebhookAsync("https://*********/api/Telega/").Wait();
and I have this webApi:
```
    public class TelegaController : ApiController
    {
        // POST: api/Telega
        public async Task<IHttpActionResult> Post(Update update)
        {
            // here I write log in txt-file
            // here I call a method SendTextMessageAsync with different replyMarkup
        }
        return Ok();
    }
```
I have try-catch in all POST-method and logs also is written in catch-block.
I build this net. framework 4.7 web app and publish it in a hosting.
I try to play with my bot and the only case when Post is called by Telegram server is when I send a NEW message!! When I edit a message or when I clck in a message-inline-buttons or in any other cases POST is NEVER called by Telegram server!!! Because I never see logs except case when I send a NEW message.
SOS!!!!

**Comment by tuscen** [comment]
@andrey-messi It's not a library problem. If you don't see any updates other than new messages than it is on Telegram. What does `getWebhookInfo` method returns? If `allowed_updates` property is not empty, than that's the culprit. 

You might accidentally set allowed updates to new messages only and forgot about it. Try calling `SetWebhookAsync` passing an empty array of `UpdateType`, this will allow all updates to be sent to your webhook:
```c#
await bot.SetWebhookAsync("https://example.com/", allowedUpdates: new UpdateType[0]);
```

**Comment by andrey-messi** [comment]
>allowedUpdates: new UpdateType[0]);
This didn't change anything.

Another problems:
1) when I upload updates on my hosting and my applications restarts then A LOT OF DUPLICATES (old messages that already have been processed before) received by method POST. Because of it my bot sends a lot of duplicates-messages to user.
2) In my webAPI I have POST method for Telegram and GET method for me to see logs in vrowser. When I upload updates on my hosting then I write a message in Telegram to my bot , and bot doesn't reply until I send a request to my GET method from my browser. This means that my bot-application starts running only when I do GET request but it is not starts when Telegram sends POST requests. This mean that after inactivity timeout my apps can be stopped on a hosting and even if a user sends message to my bot in Telegtram my application should not starts and bot can't respond to queries.
My hosting is somee.com.
