### ISSUE TITLE
Send message in Asp .net Web form

### ISSUE THREAD

**Issue by hanigamini** [TelegramBots/telegram.bot#408]
### Expected  behavior
Hello , 
I only want send message to telegram user in my asp .net web form , i have telegram id of user , 
what should I do ؟
error of Install-Package Telegram.Bot.
Could not install package 'Telegram.Bot 13.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1' .....

### Environment data

*NuGet Package Version: Package Manager Console Host Version 2.7.40911.287

*.NET Version: .NETFramework,Version=v4.5.1

*IDE: VS2013

*App: Asp .net Web form

**Comment by pouladpld** [comment]
@hanigamini I haven't tried this on older IDEs but can you try the same on VS2017?

Package is now targeting _netstandard1.1_ and I'm not sure if VS2013 understands it.

**Comment by hanigamini** [comment]
@pouladpld : 
I haven't VS 2017 and this is a risk to upgrading my web app into 2017.
There is no other way?

**Comment by pouladpld** [comment]
Removing explicit support for `net45` has caused this. Although new `netstandard1.1` covers .NET 4.5, older VS version do not follow it.

**Comment by pouladpld** [comment]
@hanigamini To use this project on old versions of VS, you need to directly reference the `Telegram.Bot.dll` file instead of its NuGet package.

See the sample I made here: 
<https://github.com/pouladpld/test-tg-bot>

And successful build status on AppVeyor using VS 2013: 
<https://ci.appveyor.com/project/pouladpld/test-tg-bot>

**Comment by hanigamini** [comment]
Thanks
