### ISSUE TITLE
Erro in Reciveing Image from bot (Using Webhook)

### ISSUE THREAD

**Issue by jourmand** [TelegramBots/telegram.bot#460]
In saving picture that sended from a member, it gave `Bad Request: invalid file id` !!

```
if (message.Type == MessageType.PhotoMessage)
{
    var file = await Bot.GetFileAsync(message.Photo.LastOrDefault()?.FileId);
}
```
---------------------------------------------------------------------------------
*NuGet Package Version:* (13.2.1)

*.NET Version:* (Mvc 4.6.1)

*IDE:* (VS2015.)

**Comment by Olfi01** [comment]
well, check the file id then maybe? try debugging and look at the message.Photo, whether there is a file id

**Comment by jourmand** [comment]
@Olfi01 See the debug screenshot! All of the `FileId` in Telegram.Bot.Types.PhotoSize hasn't FileId, FilePath & FileSize ....

![111111](https://user-images.githubusercontent.com/18249089/30239323-6471767a-956f-11e7-8b03-49d501b21e58.png)

**Comment by Olfi01** [comment]
that's really strange... can you get the photo update as json from the browser via https://api.telegram.org/botYOURTOKEN/getUpdates ?

**Comment by jourmand** [comment]
It say: "Conflict: can't use getU…while webhook is active"
But I use ngrok to test & there is JSON
![111111](https://user-images.githubusercontent.com/18249089/30239561-aa0ceb42-9574-11e7-87dd-a9326a67d4b9.png)

**Comment by Olfi01** [comment]
oh, webhook, sorry. then I suppose I know what your problem is: the built-in json parser of ASP.NET does not support newtonsoft.json attributes, so file_id and file_size won't be serialized correctly. You should change the argument of your controller from Update to string and then call `JsonConvert.DeserializeObject<Update>(jsonString)` instead. The file id should be properly included then.

**Comment by jourmand** [comment]
Its work!!!

thanks a lot
