### ISSUE TITLE
Compare to framework repo

### ISSUE THREAD

**Issue by MatthiasKauer** [TelegramBots/Telegram.Bot#617]
Hi,
I'm very interested in building something with your telegram library.
I'm a bit confused if I should use this repo or the framework repo from the same (group?) user.
Is framework the building block of the client here? Is it older, maybe obsolete by now? Is it just different?
Both are for bots that telegram users can interact with, right? Or does this lib implement a client that interacts with other bots somehow?

**Comment by Olfi01** [comment]
This is just a basic wrapping of the API Functions. Iirc the framework you are talking about let's you assign commands and triggers and stuff, so that's something different. If you want do build a bot and have it a little easier, I'd recommend the framework, but I usually write my bots only using this repo, the API. The advantage of the framework is that you don't necessarily have to check all messages incoming yourself but just add triggers. If this answers your question, close this issue ;)

**Comment by MatthiasKauer** [comment]
@Olfi01 Are you saying this library "Telegram.Bot" is more low-level (but still very usable) than the framework library (https://github.com/TelegramBots/Telegram.Bot.Framework) that I am referrring to?

**Comment by Tuscen** [comment]
@MatthiasKauer please, read issue template. We use issues only for bug reports. For anything else feel free to join out telegram group https://t.me/tgbots_dotnet.
