### ISSUE TITLE
New Package Structure

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#618]
I have a suggestion to change our package structures(after we got frameworks ready).

We make `Telegram.Bot` package a meta package similar to `Microsoft.AspnetCore.All`.

Code on this repo would be published as `Telegram.Bot.Client` so its responsibility would be constructing request & responses.

Rest of the implementations would go in specific packages depending on the type of deployment(getting updates):

**Telegram.Bot.Framework.Common** (Framework abstractions + some implementations)
 - Telegram.Bot.Client

**Telegram.Bot.Polling** (complete long polling implementation of framework)
 - Telegram.Bot.Framework.Common

**Telegram.Bot.Framework** (ASP.NET Core framework for webhooks)
 - Telegram.Bot.Framework.Common

**Telegram.Bot** (Meta package having all code for long polling & ASP.NET Core webhooks)
 - Telegram.Bot.Framework
 - Telegram.Bot.Polling

**Comment by pouladpld** [comment]
In addition, events could be removed from client package and go in the polling package. I wouldn't recommend using long polling due to performance and unnecessary use of resources (long polling! right?). Also, relying on events usually require singletons and instances that stick in memory for long.

However, we can still provide events in long polling package via a `IUpdateEventsManager` type.

**Comment by Ginrey** [comment]
Pooling is a good idea

**Comment by wiz0u** [comment]
Obsolete. We tried detaching the Polling system in separate project and it was a mess. It's now back in main project because that's what our users expect.

Now it's not impossible that in the future we rearrange the package structure for other reasons (like separate types from code), but no need to keep this old issue opened for now.
