### ISSUE TITLE
TestApiAsync shouldn't catch 404

### ISSUE THREAD

**Issue by tuscen** [TelegramBots/Telegram.Bot#622]
Bot API returns 404 on incorrectly formatted tokens. And since `TelegramBotClient` can't be instantiated with incorrectly formatted token `MakeRequestAsync` will throw` 401 Invalid Token`. So catching 404 doesn't make sense here.

**Comment by karb0f0s** [comment]
https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/src/Telegram.Bot/TelegramBotClient.cs#L270-L285
`GetMeAsync()` will throw `ApiRequestException("Invalid token", 401)` here https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/src/Telegram.Bot/TelegramBotClient.cs#L243-L245

**Comment by karb0f0s** [comment]
@tuscen @pouladpld 
I did some discovery:

1. `Should_Fail_Test_Api_Token` test is unreliable. Replacing bot token `"0:1this_is_an-invalid-token_for_tests"` with the one provided in [Telegram Bot API examples](https://core.telegram.org/bots/api#authorizing-your-bot) `123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11` (or changing few characters in real bot token, same result will be for revoked token i guess) breaks the test - it fails because [`MakeRequestAsync`](https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/src/Telegram.Bot/TelegramBotClient.cs#L243-L245) trows `new ApiRequestException("Invalid token", 401)`
https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/test/Telegram.Bot.Tests.Integ/Getting%20Updates/GettingUpdatesTests.cs#L33-L43
2. We should not check provided token in constructor [TelegramBotClient(string token, HttpClient httpClient = null)](https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/src/Telegram.Bot/TelegramBotClient.cs#L158-L166) and [TelegramBotClient(string token, IWebProxy webProxy)](https://github.com/TelegramBots/Telegram.Bot/blob/ed21285554ea3720cc70fcd8298e4cc2eeededbb/src/Telegram.Bot/TelegramBotClient.cs#L174-L188). First of all - specified regex `Regex.IsMatch(token, @"^\d*:[\w\d-_]{35}$")` is incorrect `-` should be escaped, and second - there is no actual token specification provided in official [Telegram Bot API](https://core.telegram.org/bots/api#authorizing-your-bot) documentation. I think we should leave this check to Telegram.

**Comment by karb0f0s** [comment]
Wrapping up our discussion:
- ctor should not check token format - there is no token format specification
- `ApiRequestException` should return actual error message instead of "Invalid token" to help users to understand what's actually going on. Telegram API does not provide `Invalid token` error.
- `404 HttpRequestError` could be thrown only in case of malformed API request string - either token format is totally incorrect (for example calling `TelegramBotClient("put_your_token_here")`) or making a request to nonexisting API method. This error should not be caught to inform user that something really goes wrong.
