### ISSUE TITLE
random error: Bad Request: wrong message entity

### ISSUE THREAD

**Issue by thomasd3** [TelegramBots/Telegram.Bot#848]
In my bot, sometimes I get this error:
> 
> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: wrong message entity: Wrong HTTP URL
>    at async Task<TResponse> Telegram.Bot.TelegramBotClient.MakeRequestAsync<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken)
> 

The issue is that it is quite random and rather rare. When this error happens, I resubmit the EXACT same command request and it goes through.
The code has a try / catch and the catch will try a second time, as a workaround for this bug, and it works.

Has anyone else experienced this? also, is there a way to troubleshoot it? I have put the code in my project, instead of the nuget package, to be able to trace it and the client will really do the same thing twice and the second time will work.

**Comment by karb0f0s** [comment]
do you have sample data so we can test this behavior?

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
