### ISSUE TITLE
Payment API 

### ISSUE THREAD

**Issue by ChermyaninAA** [TelegramBots/Telegram.Bot#952]
Hello. Is there a payment API implementation? [Sendinvoice ](https://core.telegram.org/bots/api#sendinvoice)method?

**Comment by avalanche759** [comment]
Yes, Payment Api is already implemented. Please, see [here](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/ITelegramBotClient.cs#L1281)

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
