### ISSUE TITLE
Wait OnMessage event with windows service

### ISSUE THREAD

**Issue by onurcansen** [TelegramBots/Telegram.Bot#958]
I have a windows service for my bot to answer commands.

Thats my basic code:
![Telegram](https://user-images.githubusercontent.com/53567590/107503492-11f85880-6bab-11eb-92cc-d7013f7bb54f.PNG)

I want it to wait for the event to be triggered from the moment the service starts until the service closes.

How can I do that.

**Comment by karb0f0s** [comment]
You can follow official docs to create a windows service project: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio).
Instead of using events it is better to handle updates polling in [HostedService](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio) using something like [Telegram.Bot.Extensions.Polling](https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling) package.

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
