### ISSUE TITLE
100% CPU when Internet connectivity is lost

### ISSUE THREAD

**Issue by wiz0u** [TelegramBots/Telegram.Bot#963]
# I found a bug to report

When Internet is lost, after 2 minutes, Telegram bot process gets to 100% CPU on a thread, looping through OnReceiveGeneralError notices for a HttpRequestException "Host unknown. (api.telegram.org:443)"

As a workaround, I added a Thread.Sleep(5000) in my handler, but I think it deserves a better fix within Telegram.Bot

### Steps to reproduce
- Run a Console bot (that does nothing in particular)
- Cut internet connectivity (wifi or ethernet)
- Wait for a few minutes
- Look for %CPU of executable in Task Manager, or place a breapoint in OnReceiveGeneralError handler

### Expected  behavior
- The TelegramBotClient should notify once that network connectivity has been lost
- then wait for network connectivity to be restored without using too much CPU
- Ideally the TelegramBotClient could notify an event to tell that network connectivity has been restored before starting to handle incoming updates from Telegram

### Actual behavior
Currently the bot is getting never-ending calls to OnReceiveGeneralError in a loop without any delay in-between
=> 100% on one CPU

### Screenshots
none

### Environment data
Tested on Windows 10

*NuGet Package Version:* (e.g. 13.0.1)
15.7.1

*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)
.NET 5.0

*IDE:* (e.g. VS2017, VS Code, etc.)
VS2019

*App:* (e.g. Desktop, iOS, Android, etc.)
Desktop Console

**Comment by Fedorus** [comment]
You have 2 public events to handle that issue:
OnReceiveError 
OnReceiveGeneralError

How you wanna handle that - its up to you

**Comment by wiz0u** [comment]
If the caller doesn't put a handler for OnReceive*Error, the default shouldn't be that it takes 100% CPU

**Comment by karb0f0s** [comment]
@wiz0u thank you for your report. we are going take care of this issue mostly by removing events altogether. you can review upcoming changes in [v15 branch](https://github.com/TelegramBots/Telegram.Bot/blob/v15/src/Telegram.Bot/TelegramBotClient.cs).

**Comment by karb0f0s** [comment]
I see why this is happening: due to failed `GetUpdatesAsync` request inside the infinite loop error handlers are invoked constantly. Although I don't see a good way to handle this situation inside this method. A better approach would be implementing backoff policies for `HttpClient`, which will defer these errors. You can find examples in this article: [Implement HTTP call retries with exponential backoff with IHttpClientFactory and Polly policies](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly)
