### ISSUE TITLE
AnswerPreCheckoutQueryAsync all time return error

### ISSUE THREAD

**Issue by mirjahongir** [TelegramBots/Telegram.Bot#967]
Hi I have problem with AnswerPreCheckoutQueryAsync method whan I am send response in telegram client I see all time error
 but I am send success 

_client.AnswerPreCheckoutQueryAsync(preCheckoutQuery.Id)

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/But_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Rankors** [comment]
I have the same problem, how did you solve the problem?
