### ISSUE TITLE
Virtual methods at class TelegramBotClient

### ISSUE THREAD

**Issue by P9os** [TelegramBots/Telegram.Bot#995]
## Virtual methods at class TelegramBotClient
***
Please add modificator virtual for methods at class  [TelegramBotClient](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs). For simple override method without use pattern adapter.

**Comment by Fedorus** [comment]
if you`ll look at v15 branch you'll see that almost all methods will be replaced with extension methods

**Comment by tuscen** [comment]
I'm planning on experimenting on an internal request pipeline instead of virtual methods for intercepting requests. But I can't give any estimations when it will be done.

@Fedorus It won't help with the usecase for virtual methods. In vnext only `MakeRequestAsync` will be left and in that case we would have to make it virtual for easier use with inheritance. But I'm generally not a fan of this solution in with our client.

**Comment by tuscen** [comment]
Done in #1102
